"""
doctors_seed.py — demo specialist directory.

Same disclosed-as-fictional profiles the Figma export shipped with
("Demo directory... do not describe real practitioners"). Moved server-side
so booking against them can actually persist and reduce availability.
"""

DOCTORS = [
    {
        "id": "d1",
        "name": "Dr. Sarah Chen",
        "specialty": "Ophthalmologist",
        "clinic": "Pacific Vision Center",
        "location": "San Francisco, CA",
        "rating": 4.9,
        "reviews": 247,
        "initials": "SC",
        "avatarColor": "#1A4A6B",
        "baseSlots": [
            {"date": "2026-09-02", "times": ["09:00", "11:30", "14:00"]},
            {"date": "2026-09-04", "times": ["10:00", "15:30"]},
            {"date": "2026-09-08", "times": ["09:30", "13:00", "16:00"]},
        ],
        "consultationType": "Both",
        "experience": 15,
        "bio": "Board-certified ophthalmologist specializing in comprehensive eye care and corneal diseases.",
    },
    {
        "id": "d2",
        "name": "Dr. Marcus Webb",
        "specialty": "Retina Specialist",
        "clinic": "Advanced Retinal Institute",
        "location": "Los Angeles, CA",
        "rating": 4.8,
        "reviews": 189,
        "initials": "MW",
        "avatarColor": "#2D1A6B",
        "baseSlots": [
            {"date": "2026-09-03", "times": ["11:00", "14:30"]},
            {"date": "2026-09-05", "times": ["10:00", "15:00"]},
            {"date": "2026-09-09", "times": ["09:00", "12:00"]},
        ],
        "consultationType": "In-person",
        "experience": 22,
        "bio": "Fellowship-trained retina specialist with expertise in diabetic retinopathy and macular degeneration.",
    },
    {
        "id": "d3",
        "name": "Dr. Priya Sharma",
        "specialty": "Optometrist",
        "clinic": "ClearVision Optical",
        "location": "New York, NY",
        "rating": 4.7,
        "reviews": 312,
        "initials": "PS",
        "avatarColor": "#1A6B4A",
        "baseSlots": [
            {"date": "2026-09-02", "times": ["10:00", "14:00", "16:00"]},
            {"date": "2026-09-03", "times": ["09:00", "13:00"]},
            {"date": "2026-09-05", "times": ["11:00", "15:00"]},
        ],
        "consultationType": "Both",
        "experience": 8,
        "bio": "Comprehensive optometrist specializing in refractive errors, contact lens fitting, and pediatric eye care.",
    },
    {
        "id": "d4",
        "name": "Dr. Aiden Park",
        "specialty": "Ophthalmologist",
        "clinic": "EyeHealth Partners",
        "location": "Chicago, IL",
        "rating": 4.8,
        "reviews": 203,
        "initials": "AP",
        "avatarColor": "#6B3A1A",
        "baseSlots": [
            {"date": "2026-09-04", "times": ["09:30", "14:30"]},
            {"date": "2026-09-07", "times": ["10:00", "13:30", "16:30"]},
        ],
        "consultationType": "Telehealth",
        "experience": 12,
        "bio": "Glaucoma specialist with extensive experience in minimally invasive glaucoma surgery (MIGS).",
    },
    {
        "id": "d5",
        "name": "Dr. Fatima Al-Hassan",
        "specialty": "Retina Specialist",
        "clinic": "Vision Research Center",
        "location": "Boston, MA",
        "rating": 4.9,
        "reviews": 156,
        "initials": "FA",
        "avatarColor": "#1A5A6B",
        "baseSlots": [
            {"date": "2026-09-05", "times": ["09:00", "12:00"]},
            {"date": "2026-09-10", "times": ["14:00", "16:00"]},
        ],
        "consultationType": "Both",
        "experience": 18,
        "bio": "Expert in age-related macular degeneration and inherited retinal diseases, with over 50 published studies.",
    },
    {
        "id": "d6",
        "name": "Dr. Carlos Rivera",
        "specialty": "Optometrist",
        "clinic": "Neighborhood Eye Care",
        "location": "Miami, FL",
        "rating": 4.6,
        "reviews": 428,
        "initials": "CR",
        "avatarColor": "#4A6B1A",
        "baseSlots": [
            {"date": "2026-09-02", "times": ["08:30", "10:30", "14:00", "16:00"]},
            {"date": "2026-09-03", "times": ["09:00", "11:00", "15:00"]},
            {"date": "2026-09-04", "times": ["10:00", "14:30"]},
        ],
        "consultationType": "In-person",
        "experience": 10,
        "bio": "Primary eye care provider focused on preventive eye health and low vision rehabilitation.",
    },
]
